ACadSharp.Tests/Common/DocumentIntegrity.cs, ACadSharp/CadDocument.cs, ACadSharp/IO/DWG/DwgObjectSectionReader.cs, ACadSharp/IO/Templates/CadDictionaryTemplate.cs, ACadSharp/LayoutCollection.cs, ACadSharp/Objects/Layout.cs
Layout collection fix to not be assigned with a handle
=> Layout management

ACadSharp/CadUtils.cs, ACadSharp/DxfPropertyBase.cs, ACadSharp/Entities/AttributeBase.cs, ACadSharp/Entities/TextEntity.cs, ACadSharp/Entities/TextVerticalAlignmentType.cs, ACadSharp/Entities/VerticalAlignmentType.cs, ACadSharp/Header/CadHeader.cs, ACadSharp/IO/DWG/DwgHeaderReader.cs, ACadSharp/IO/DWG/DwgObjectSectionReader.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfHeaderSectionWriter.cs, ACadSharp/IO/DXF/DxfWriter.cs, ACadSharp/Tables/DimensionStyle.cs, ACadSharp/Tables/UCS.cs, ACadSharp/Types/Units/AngularUnitFormat.cs
Added header variables to be accepted by Autocad in the dxf format
=> Cad header variables

ACadSharp/Entities/Spline.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/Templates/CadSplineTemplate.cs
I was inspired by MLine Entity implementation and tried to follow implementation rules as in other Entities.
I am not sure how to set KnotParametrization flag. I see intensive development here, so I hope it can help.
=> Implementation of Spline reading for DxfSectionReaderBase

ACadSharp/Entities/TextEntity.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfBinaryReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfBlockSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfReaderBase.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTextReader.cs, ACadSharp/IO/DXF/DxfStreamReader/IDxfStreamReader.cs
Internal fix for dxf readers binary/text
=> Dxf reader wrapper

ACadSharp/IO/CadDocumentBuilder.cs, ACadSharp/IO/CadReaderBase.cs, ACadSharp/IO/DWG/DwgObjectSectionReader.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DXF/DxfDocumentBuilder.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfBlockSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfEntitiesSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, ACadSharp/IO/Templates/CadDimensionStyleTemplate.cs, ACadSharp/IO/Templates/CadLineTypeTemplate.cs, ACadSharp/IO/Templates/CadMLStyleTemplate.cs, ACadSharp/IO/Templates/CadTableTemplate.cs, ACadSharp/IO/Templates/CadViewportTemplate.cs, ACadSharp/IO/Templates/DwgBlockCtrlObjectTemplate.cs
Change ```OnNotification``` to an event
=> On notification refactor

ACadSharp.Tests/IO/IOTests.cs, ACadSharp/IO/DWG/DwgObjectSectionReader.cs, ACadSharp/IO/DXF/DxfDocumentBuilder.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfBlocksSectionWriter.cs, ACadSharp/IO/Templates/CadBlockRecordTemplate.cs, ACadSharp/IO/Templates/CadLayoutTemplate.cs, ACadSharp/Objects/Layout.cs, ACadSharp/Objects/PlotSettings.cs, ACadSharp/Tables/BlockRecord.cs
- Viewport fix to point to the Block Record as the owner, the layout links all the viewports to the block
=> Viewport refactor

ACadSharp/Entities/Ellipse.cs, ACadSharp/IO/DWG/DwgObjectSectionReader.cs
- Fix ellipse reading for the Endpoint field
- Updated documentation
=> issue42 ellipse fix

ACadSharp/IO/DWG/DwgObjectSectionReader.cs, ACadSharp/IO/Templates/CadHatchTemplate.cs
- Fix the reader for a polyline as boundary.
=> read hatch fix

ACadSharp/IO/DWG/DwgObjectSectionReader.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/Templates/DwgColorTemplate.cs
This PR is meant to complement the implementation of https://github.com/DomCR/ACadSharp/pull/77
In certain cases the `DwgObjectSectionReader` gets stuck in an infinite loop, this PR fix this issue
=> Issue 63 Slow Read

ACadSharp/Entities/TextVerticalAlignmentType.cs
Correction for vertical justification order.
=> Fix for TextVerticalAlignmentType

ACadSharp.Tests/Common/AssertUtils.cs, ACadSharp.Tests/Common/EntityComparator.cs, ACadSharp.Tests/TestVariables.cs, ACadSharpInternal.Tests/ACadSharpInternal.Tests.csproj
Adjustment in the equality tolerance for double values.
=> Test value tolerance

ACadSharp.Examples/ACadSharp.Examples.csproj, ACadSharp.Tests/ACadSharp.Tests.csproj, ACadSharp.sln, ACadSharp/ACadSharp.csproj, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, ACadSharpInternal.Tests/ACadSharpInternal.Tests.csproj, Directory.Build.props
Add the TEST environment variable as a tool for testing.
=> Test variable

ACadSharp.Tests/Common/EntityFactory.cs, ACadSharp.Tests/IO/DXF/DxfWriterTests.cs, ACadSharp.Tests/IO/IOTestsBase.cs, ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/Entities/Insert.cs, ACadSharp/Entities/TextEntity.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, ACadSharp/IO/DXF/DxfWriter.cs
Implement missing entities into the `DxfWriter`
https://github.com/DomCR/ACadSharp/issues/104
=> Dxf writer entities

ACadSharp.Tests/IO/IOTestsBase.cs, ACadSharp/DxfSubclassMarker.cs, ACadSharp/Entities/ClipType.cs, ACadSharp/Entities/ImageDisplayFlags.cs, ACadSharp/Entities/Wipeout.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderBase.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, ACadSharp/IO/Templates/CadWipeoutTemplate.cs, ACadSharp/Objects/FaceColorMode.cs, ACadSharp/Objects/FaceLightingModelType.cs, ACadSharp/Objects/FaceLightingQualityType.cs, ACadSharp/Objects/FaceModifierType.cs, ACadSharp/Objects/VisualStyle.cs
Allows to explore the `Entity` fields in the `DwgObjectReader`.
=> Dwg reader exploration

ACadSharp.Examples/Program.cs, ACadSharp/IO/CadWriterBase.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DWG/DwgWriter.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfAsciiWriter.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfBinaryWriter.cs, ACadSharp/IO/DXF/DxfStreamWriter/IDxfStreamWriter.cs, ACadSharp/IO/DXF/DxfWriter.cs
Close the stream once the writer is done to fix invalid streams as a result.
https://github.com/DomCR/ACadSharp/issues/115
=> Close the stream for writers

ACadSharp/ExtendedDataCollection.cs
I added Dictionary get functions to ExtendedDataCollection because I need them in a project.
IMHO it would also be possible to inherit the ExtendedDataCollection from Dictionary, but I was not willing to change this because it might have an unforeseen impact on other code parts.
- This is just a small contribution and it is just because I require it. If it is not of interest for the project at all, please reject.
Thanks for your effort. This project increased my parsing performance of DWG file by factor 5 compared to http://www.ivancad.com/
=> Added Get function for ExtendedDataCollection

ACadSharp/Entities/Arc.cs, ACadSharp/Entities/Dimension.cs, ACadSharp/Entities/DimensionLinear.cs, ACadSharp/Entities/Hatch.cs, ACadSharp/Entities/Insert.cs, ACadSharp/Entities/Point.cs, ACadSharp/Entities/Shape.cs, ACadSharp/Entities/TextEntity.cs, ACadSharp/Entities/Vertex.cs, ACadSharp/Entities/ViewPort.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, ACadSharp/Objects/MLStyle.cs, ACadSharp/Tables/LineTypeSegment.cs, ACadSharp/Tables/TextStyle.cs, ACadSharp/Tables/VPort.cs, ACadSharp/Tables/View.cs, ACadSharp/Types/DxfReferenceType.cs
Change all the Dxf angles from Degrees to Radians in the reader and Radians to Degrees in the writers
[Issue 104 fix arc dxf writer](https://github.com/DomCR/ACadSharp/pull/124)
=> Dxf angles

ACadSharp/Blocks/Block.cs, ACadSharp/IO/CadDocumentBuilder.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfBlockSectionReader.cs
Fix the block reading by finding the parent by name.
=> Issue 127 dxf reader header set

ACadSharp.Examples/Program.cs, ACadSharp.Tests/Tables/BlockRecordTests.cs, ACadSharp/Tables/BlockRecord.cs
=> Fix BlockRecord.Clone

ACadSharp.Tests/IO/DXF/DxfReaderTests.cs, ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/ACadSharp.csproj, ACadSharp/CadUtils.cs, ACadSharp/Header/CadHeader.cs, ACadSharp/IO/CadReaderBase.cs, ACadSharp/IO/CadWriterBase.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgHeaderReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectSectionReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderBase.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgFileHeaderWriterAC15.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgFileHeaderWriterAC18.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgFileHeaderWriterAC21.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgFileHeaderWriterBase.cs, ACadSharp/IO/DWG/DwgWriter.cs, ACadSharp/IO/DWG/FileHeaders/DwgFileHeader.cs, ACadSharp/IO/DWG/FileHeaders/DwgFileHeaderAC15.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfBinaryReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTextReader.cs, ACadSharp/IO/DXF/DxfWriter.cs, ACadSharpInternal.Tests/DwgHandleWriterTests.cs, ACadSharpInternal.Tests/DwgHeaderWriterTests.cs, ACadSharpInternal.Tests/DwgObjectWriterTests.cs
Implementation of the different file encoding for strings.
- The dependency will be removed using the module in CSUtilities.Text once implemented
=> Issue 108 encoding support

ACadSharp/Entities/Hatch.BoundaryPath.Ellipse.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
Fix for `BoundaryPath.Ellipse`
=> issue-147-HatchBoundaryPathEllipse-MinortoMajorRatio

ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
=> Issue-146 fix reactors resolve

ACadSharp/IO/Templates/CadInsertTemplate.cs
Fix for the block reference by name when reading a dxf
=> Issue-152 insert block always null

ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/DxfPropertyBase.cs, ACadSharp/Header/CadHeader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfHeaderSectionWriter.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs, ACadSharp/IO/DXF/DxfWriter.cs, ACadSharp/IO/DXF/DxfWriterOptions.cs
Implement the option to manage the header variables in the dxf writer.
=> Issue-153 write basic header variables

ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
Fix the IsClosed flag for 3D Polylines
=> Issue-159 Fix the IsClosed flag for 3D Polylines 

ACadSharp.Tests/CadDocumentTests.cs, ACadSharp.Tests/Entities/PolylineTest.cs, ACadSharp.Tests/Entities/SeqendTests.cs, ACadSharp/CadDocument.cs, ACadSharp/CadObjectCollection.cs, ACadSharp/Entities/Vertex2D.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, ACadSharp/IO/Templates/CadInsertTemplate.cs, ACadSharp/IO/Templates/CadPolyLineTemplate.cs, ACadSharp/IO/Templates/CadPolyfaceMeshTemplate.cs, ACadSharp/ISeqendColleciton.cs, ACadSharp/SeqendCollection.cs
=> Seqend management

ACadSharp.Tests/IO/IOTests.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterBase.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgmMergedStreamWriter.cs, ACadSharp/IO/DWG/DwgStreamWriters/IDwgStreamWriter.cs
Implement Hatch for DwgWriter.
=> DwgWriter Hatch

ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC18.cs
`ReadEnColor` fix for true color
=> ReadEnColor fix

ACadSharp/Exceptions/DwgNotSupportedException.cs, ACadSharp/Exceptions/DxfNotSupportedException.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
=> Dxf reader version check

ACadSharp.Tests/IO/DWG/DwgWriterSingleObjectTests.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC18.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC18.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterBase.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgmMergedStreamWriter.cs, ACadSharp/IO/DWG/DwgStreamWriters/IDwgStreamWriter.cs
Implement the writer for entity color
=> Issue 217 dwg writer entity color

ACadSharp.Tests/Entities/DimensionTests.cs, ACadSharp/Entities/Dimension.cs, ACadSharp/Entities/DimensionType.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/Templates/CadDimensionTemplate.cs
=> Dimension flags

ACadSharp.Tests/Entities/ArcTests.cs, ACadSharp.Tests/Entities/LwPolylineTest.cs, ACadSharp.Tests/Entities/PolylineTest.cs, ACadSharp/DxfPropertyBase.cs, ACadSharp/Entities/Arc.cs, ACadSharp/Entities/PolyLine.cs, ACadSharp/Header/CadHeader.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfStreamWriterBase.cs, ACadSharp/MathUtils.cs
Refactor for IVector in CSMath
- https://github.com/DomCR/CSUtilities/pull/4
=> IVector refactor

ACadSharp/ExtendedDataCollection.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/Templates/CadTemplate.cs
Handles in extended data fix for dwg
=> Handles in extended data fix for dwg

ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/Tables/TableEntry.cs
Fix for TextStyles with file references
=> TextStyles file reference fix

ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgAuxHeaderWriter.cs
Remove Educational plot stamp.
=> Issue-245 Remove-student-version-watermark

ACadSharp.Tests/IO/IOTestsBase.cs, ACadSharp.Tests/TestVariables.cs
Help running limited tests under linux
=> skip accoreconsole.exe on linux by default

ACadSharp.Tests/ACadSharp.Tests.csproj
less forks, easier debugging
https://devblogs.microsoft.com/dotnet/introducing-ms-test-runner/
=> EnableMSTestRunner as single exe

ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
Ignore Objects an entities that are not fully implemented.
=> DwgWriter ignore not implemented objects end entities

ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgAppInfoReader.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgAppInfodWriter.cs
Refactor `DwgAppInfodWriter` for a better and more accurate implementation.
https://github.com/DomCR/ACadSharp/commit/9ff72ecbd19d8122b43defb296742bb4450f01cc
=> DwgAppInfodWriter refactor

ACadSharp/Entities/Dimension.cs
Short description about this PR
- Add the links of issues or PR related to this one.
- Things to consider during the review of this PR.
=> 20231206 nka 151 dimension text default logic and formatting

ACadSharp/Entities/IText.cs, ACadSharp/Entities/MText.cs, ACadSharp/Entities/TextEntity.cs, ACadSharp/IO/Templates/CadTextEntityTemplate.cs
Text interface to wrap the common properties
=> Common interface mtext text

ACadSharp/Tables/DimensionStyle.cs
=> 20240304 mme dimension style comment

ACadSharp.Tests/Header/CadHeaderTests.cs, ACadSharp/Header/CadHeader.cs
Make sure that all the linked objects in the Header are linked to the ones in the document in case that it belongs to one.
=> CadHeader linked with CadDocument

ACadSharp/CadObject.cs, ACadSharp/Header/CadHeader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgHeaderReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgHeaderWriter.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, ACadSharp/Tables/DimensionStyle.cs, ACadSharp/Tables/TextArrowFitType.cs, ACadSharp/Tables/TextDirection.cs
DimensionStyle properties defaults.
=> Dim style defaults

ACadSharp/DxfPropertyBase.cs, ACadSharp/Entities/Hatch.BoundaryPath.Polyline.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
Hatch.BoundaryPath.Polyline implementation for DxfReader and fix for DxfWriter
=> Issue 303 DxfReader hatchboundarypathpolyline

ACadSharp/Classes/DxfClassCollection.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC24.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterBase.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgmMergedStreamWriter.cs, ACadSharp/IO/DWG/DwgStreamWriters/IDwgStreamWriter.cs, ACadSharp/Objects/CadDictionary.cs
Implement the `CadObject` linked to a `DxfClass` for the `DwgWriter`
* https://github.com/DomCR/ACadSharp/pull/189
* https://github.com/DomCR/ACadSharp/pull/300
=> DwgWriter unlisted objects

ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/Attributes/CadSystemVariableAttribute.cs, ACadSharp/CadObject.cs, ACadSharp/Header/CadHeader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfHeaderSectionWriter.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfTablesSectionWriter.cs, ACadSharp/IO/Templates/CadBlockRecordTemplate.cs, ACadSharp/IO/Templates/CadTableTemplate.cs, ACadSharp/PropertyReflection.cs, ACadSharp/Tables/Collections/Table.cs, ACadSharp/Tables/Collections/TextStylesTable.cs, ACadSharp/Tables/TableEntry.cs, ACadSharp/Types/DxfReferenceType.cs
Fix the name assignation for table entries when the name is an empty string.
`ACadSharp` will assign a random name if an entry doesn't have one.
=> Issue 317 dwg textstyle using the file name

.editorconfig, ACadSharp.Tests/IO/IOTests.cs, ACadSharp.Tests/Tables/Collections/BlockRecordTests.cs, ACadSharp.Tests/Tables/Collections/TextStylesTableTests.cs, ACadSharp.Tests/Tables/TableEntryTests.cs, ACadSharp/Attributes/DxfCodeValueAttribute.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfTablesSectionWriter.cs, ACadSharp/Tables/Collections/AppIdsTable.cs, ACadSharp/Tables/Collections/BlockRecordsTable.cs, ACadSharp/Tables/Collections/DimensionStylesTable.cs, ACadSharp/Tables/Collections/LayersTable.cs, ACadSharp/Tables/Collections/LineTypesTable.cs, ACadSharp/Tables/Collections/Table.cs, ACadSharp/Tables/Collections/TextStylesTable.cs, ACadSharp/Tables/Collections/UCSTable.cs, ACadSharp/Tables/Collections/VPortsTable.cs, ACadSharp/Tables/Collections/ViewsTable.cs, ACadSharp/Tables/TableEntry.cs, ACadSharp/Tables/TextStyle.cs
Set a quick flag to determine if `TextStyle` is a reference from a shape file. 
Adapt the Readers to avoid writing the name of the style if is from a shape file.
=> Issue 321 textstyle isshape flag

ACadSharp/CadDocument.cs, ACadSharp/IO/DXF/DxfDocumentBuilder.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfEntitiesSectionReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, ACadSharp/IO/Templates/CadBlockRecordTemplate.cs, ACadSharp/IO/Templates/CadEntityTemplate.cs
Set all the objects in the ENTITIES section for the DXF files to the model as default.
=> Dxf entities default owner

ACadSharp.Tests/IO/DXF/DxfReaderTests.cs, ACadSharp/CadDocument.cs, ACadSharp/IO/CadDocumentBuilder.cs, ACadSharp/IO/DWG/DwgDocumentBuilder.cs, ACadSharp/IO/DXF/DxfDocumentBuilder.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/Templates/CadEntityTemplate.cs
Read a single section in a dxf file.
=> Dxf modular reading

ACadSharp/ACadSharp.csproj, ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
Associated block for layout fix when writing the handle.
=> DxfWriter layout fix

ACadSharp/IO/DXF/DxfStreamWriter/DxfStreamWriterBase.cs, ACadSharp/IO/DXF/DxfStreamWriter/IDxfStreamWriter.cs
See Issue https://github.com/DomCR/ACadSharp/issues/337
=> #337 Implement WriteCmColor

ACadSharp/Entities/CadImageBase.cs
Fix for the AssignDocument when ImageDefinitions entry is null.
=> Image base fix

ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/CadDocument.cs, ACadSharp/Entities/CadImageBase.cs, ACadSharp/IO/CadDocumentBuilder.cs, ACadSharp/IO/DWG/DwgDocumentBuilder.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, ACadSharp/IO/DXF/DxfDocumentBuilder.cs
Create default collections before building the document to ensure integrity.
=> Create default elements fix

ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp/IO/CadDocumentBuilder.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs
Fix the DxfReader to be able to read almost any kind of dxf provided by other softwares.
=> Irregular dxf no version

ACadSharp.Tests/Common/CadObjectTestUtils.cs, ACadSharp.Tests/Entities/InsertTest.cs, ACadSharp.Tests/Entities/PolylineTest.cs, ACadSharp.Tests/Tables/BlockRecordTests.cs, ACadSharp/Entities/Insert.cs, ACadSharp/Entities/PolyFaceMesh.cs, ACadSharp/Entities/PolyLine.cs, ACadSharp/Entities/PolyfaceMesh.cs, ACadSharp/Tables/BlockRecord.cs
Fix a bug related to the clone method and the linked collections.
=> Cad object collection clone fix

ACadSharp.Tests/CadDocumentTests.cs, ACadSharp/CadDocument.cs, ACadSharp/Objects/CadDictionary.cs, ACadSharp/Objects/Collections/ObjectDictionaryCollection.cs
Method to create the default settings for `CadDocument`, this may fix possible errors for irregular files.
=> Cad document create defaults

ACadSharp/Entities/IText.cs, ACadSharp/Entities/MText.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
=> fix writer annotation text

ACadSharp.Tests/IO/CadReaderTestsBase.cs, ACadSharp/IO/CadReaderBase.cs, ACadSharp/IO/CadReaderConfiguration.cs, ACadSharp/IO/CadWriterBase.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DWG/DwgReaderConfiguration.cs, ACadSharp/IO/DWG/DwgWriter.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfReaderConfiguration.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfHeaderSectionWriter.cs, ACadSharp/IO/DXF/DxfWriter.cs, ACadSharp/IO/DXF/DxfWriterConfiguration.cs, ACadSharp/IO/ICadReader.cs
Fix the `CadWriter` configuration setup.
=> Writer options

ACadSharp/IO/DWG/DwgReader.cs
=> Encoding fix for Dwg

ACadSharp.Tests/IO/WriterSingleObjectTests.cs, ACadSharp/DxfPropertyBase.cs, ACadSharp/Entities/Entity.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC18.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC18.cs, ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, ACadSharp/Transparency.cs
Fix the writing of the Transparency values for Dxf and Dwg.
=> Issue-398 write transparency value

.config/dotnet-tools.json, ACadSharp/INamedCadObject.cs, ACadSharp/Objects/NonGraphicalObject.cs
Add a note the the CadDictionary Name will not be saved.
=> Issue 397 cad dictionary documentation

ACadSharp/Color.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC18.cs
Fix the order of bytes for true color.
=> Issue 407 fix true color value

ACadSharp.Tests/IO/WriterSingleObjectTests.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs, ACadSharp/Tables/LineType.cs, ACadSharp/Tables/LineTypeSegment.cs
DwgWriter fix for Linetypes with segments.
=> DwgWriter fix for Linetypes with segments

ACadSharp.Tests/IO/LocalSampleTests.cs, ACadSharp.Tests/IO/WriterSingleObjectTests.cs, ACadSharp.Tests/Internal/DwgHandleWriterTests.cs, ACadSharp.Tests/Internal/DwgHeaderWriterTests.cs, ACadSharp.Tests/Internal/DwgObjectWriterTests.cs, ACadSharp.Tests/Objects/CadDictionaryTests.cs, ACadSharp.Tests/Objects/LayoutTests.cs, ACadSharp.Tests/Objects/NonGraphicalObjectTests.cs, ACadSharp.Tests/TestVariables.cs, ACadSharp/IO/CadWriterBase.cs, ACadSharp/IO/DWG/DwgReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgClassesReader.cs, ACadSharp/IO/DWG/DwgStreamReaders/DwgHandleReader.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgAuxHeaderWriter.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgClassesWriter.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgHeaderWriter.cs, ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs, ACadSharp/IO/DWG/DwgWriter.cs, ACadSharp/IO/DXF/DxfReader.cs, ACadSharp/IO/DXF/DxfStreamReader/DxfTextReader.cs, ACadSharp/Objects/CadDictionary.cs, ACadSharp/Objects/Collections/ObjectDictionaryCollection.cs, ACadSharp/Objects/NonGraphicalObject.cs, ACadSharp/Objects/Scale.cs
Fix the text encoding for dwg writer.
=> Issue 409 text encoding fix

.github/workflows/build.yml, .github/workflows/wiki-gen.yml, update-wiki.sh
=> wiki generation fix

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC18.cs
=> header color index fix

src/ACadSharp.Tests/Entities/ArcTests.cs, src/ACadSharp/Objects/SortEntitiesTable.cs
Fix for sort entities table when entities have no owner.
=> Sort entities table fix

src/ACadSharp/Entities/AttributeBase.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs, src/ACadSharp/IO/Templates/CadAttributeTemplate.cs
Implement Attribute Multiline.
=> Issue-405 Implement Attribute Multiline

src/ACadSharp.Tests/CadObjectTests.cs, src/ACadSharp.Tests/Entities/EntityTests.cs, src/ACadSharp.Tests/IO/DWG/DwgReaderTests.cs, src/ACadSharp.Tests/IO/DXF/DxfReaderTests.cs, src/ACadSharp/IO/CadDocumentBuilder.cs, src/ACadSharp/IO/CadReaderConfiguration.cs, src/ACadSharp/IO/DWG/DwgDocumentBuilder.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs, src/ACadSharp/IO/DXF/DxfDocumentBuilder.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs, src/ACadSharp/IO/Templates/CadUnknownEntityTemplate.cs, src/ACadSharp/Objects/UnknownNonGraphicalObject.cs
Implements `NoneGraphicalObject` to read unknown objects and add the information to the `CadDocument`.
=> Unknown None Graphical Object

src/ACadSharp.Tests/IO/LocalSampleTests.cs, src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
Enable the DwgWriter to write `AttributeEntity`.
=> Issue 447 enable dwgwriter for attribute entities

src/ACadSharp.Tests/Common/AssertUtils.cs, src/ACadSharp.Tests/Entities/ViewportTests.cs, src/ACadSharp/Entities/Viewport.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs, src/ACadSharp/MathUtils.cs, src/ACadSharp/Tables/DimensionStyle.cs
Viewport select entities returns the entities that are in the view box of the viewport in the model.
=> Viewport select entities

src/ACadSharp/CadDocument.cs, src/ACadSharp/Entities/Viewport.cs, src/ACadSharp/Objects/PlotSettings.cs, src/ACadSharp/Objects/Scale.cs, src/ACadSharp/Tables/BlockRecord.cs, src/ACadSharp/Types/LineWeightType.cs
Add the real scale factor for the viewport.
=> Viewport scale factor

src/ACadSharp/IO/Templates/CadTemplate.cs
Fix to read Extended data in dxf files.
=> Read EData in Dxf files

.github/workflows/publish.yml
Setup an action to publish on release.
=> Publish nuget on release

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgHandleWriter.cs
Fix for netstandard20 compatibility.
=> netstandard20

src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs, src/ACadSharp/Objects/CadDictionaryWithDefault.cs
Fix for Dictionary with default and anonymous blocks.
=> Dictionary with def & blocks

.github/workflows/coveralls.yml, src/ACadSharp.Tests/ACadSharp.Tests.csproj, src/ACadSharp.Tests/Common/DocumentIntegrity.cs, src/ACadSharp.Tests/Entities/ArcTests.cs, src/ACadSharp.Tests/IO/DXF/DxfReaderTests.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/Templates/BlockVisibilityParameterTemplate.cs, src/ACadSharp/MathUtils.cs
Added net framework support for the tests.
=> Issue 515 net framework fix

src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/Tables/TextStyle.cs
Fix the naming for TextStyles linked to a shx file.
=> text style name fix

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/Header/CadHeader.cs, src/ACadSharp/IO/CadWriterConfiguration.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs, src/ACadSharp/IO/DWG/DwgWriter.cs, src/ACadSharp/IO/DWG/DwgWriterConfiguration.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfBlocksSectionWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfClassesSectionWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfEntitiesSectionWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfHeaderSectionWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfStreamWriterBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfTablesSectionWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/IDxfStreamWriter.cs, src/ACadSharp/IO/DXF/DxfWriter.cs, src/ACadSharp/XData/ExtendedDataControlString.cs
Fix missing implementation for XData real, and add a configuration flag.
=> Dwg writer xdata fix

src/ACadSharp.Tests/IO/IOTests.cs, src/ACadSharp.Tests/XData/ExtendedDataTests.cs, src/ACadSharp/CadObject.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, src/ACadSharp/XData/ExtendedData.cs, src/ACadSharp/XData/ExtendedDataCollection.cs
Link the XData appids with the document assigned.
=> Issue 534 XData link cad document

src/ACadSharp/IO/Templates/CadBlockVisibilityParameterTemplate.cs
Fix to add states into the dynamic properties.
=> issue 552 add states

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/Tables/LineType.cs
Fix for the linetype clone method.
=> Issue 565 linetype clone

src/ACadSharp/Objects/SortEntitiesTable.cs
Fix for cases where the sortentities table owner doesn't match with the entity owner.
=> issue 547 sortentites fix

src/ACadSharp.Tests/ACadSharp.Tests.csproj, src/ACadSharp.Tests/Common/AssertUtils.cs, src/ACadSharp.Tests/Common/EntityComparator.cs, src/ACadSharp/Objects/SortEntitiesTable.cs
Remove the MSTest dependency and use Xunit only.
=> remove MSTest dependency

src/ACadSharp.Tests/CadObjectTests.cs, src/ACadSharp.Tests/Common/CadObjectTestUtils.cs, src/ACadSharp.Tests/IO/IOTests.cs, src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/CadObject.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfTablesSectionWriter.cs, src/ACadSharp/IO/Templates/CadTemplate.cs
Refactor the reactors in CadObject to be written.
=> write reactors

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp.Tests/Objects/GroupTests.cs, src/ACadSharp/CadDocument.cs, src/ACadSharp/CadObject.cs, src/ACadSharp/DxfFileToken.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs, src/ACadSharp/IO/Templates/CadGroupTemplate.cs, src/ACadSharp/IObservableCadCollection.cs, src/ACadSharp/Objects/Collections/GroupCollection.cs, src/ACadSharp/Objects/Group.cs, src/CodeMaid.config
Fix the group entities collection so is written correctly.
=> Write Group

src/ACadSharp/Exceptions/CadNotSupportedException.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgClassesReader.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderBase.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgClassesWriter.cs, src/CodeMaid.config
Fix for the writer related to this reader implementation:
- https://github.com/DomCR/ACadSharp/pull/582
This PR will be merged if the 582-PR doesn't present any issues.
#580
=> Dwg DxfClasses writer fix

.github/ISSUE_TEMPLATE/bug_report.md, src/ACadSharp.Tests/Entities/ArcTests.cs, src/ACadSharp/ACadSharp.csproj
Fix for the merge method in BoundingBox.
=> Issue 584 boundingbox merge fix

src/ACadSharp.Tests/Entities/InsertTest.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Insert.cs
Fix for the insert scale property.
=> Insert Scale

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Header/CadHeader.cs, src/ACadSharp/IO/DWG/DwgHeaderHandlesCollection.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgHeaderWriter.cs
Fix for the dimension style override.
=> Issue 592 style override

src/ACadSharp.Tests/Entities/InsertTest.cs, src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Insert.cs, src/ACadSharp/IO/Templates/CadInsertTemplate.cs
Link between AttributeDef and AttributeEntity fix.
=> issue 595 attributes fix

src/ACadSharp.Examples/Entities/LineExample.cs
Just add a new file in the examples, creating some lines.
=> add lines example file

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/CadDocument.cs, src/ACadSharp/Header/CadHeader.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgHeaderReader.cs
Solves an issue created in #606 regarding the `HandSeed` in the header.
=> addCadObject fix

src/ACadSharp.Tests/IO/IOTests.cs, src/ACadSharp.Tests/IO/LocalSampleTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/CadDocument.cs, src/ACadSharp/Classes/DxfClassCollection.cs, src/ACadSharp/IO/CadWriterBase.cs, src/ACadSharp/IO/CadWriterConfiguration.cs, src/ACadSharp/IO/DXF/DxfReader.cs, src/ACadSharp/IO/Templates/CadBlockRecordTemplate.cs, src/ACadSharp/Objects/CadDictionary.cs
Fix for invalid `DxfClasses` read from dxf files.
=> Issue 612 dxf to dwg

src/ACadSharp.Tests/Common/AssertUtils.cs, src/ACadSharp.Tests/Entities/ArcTests.cs, src/ACadSharp.Tests/Entities/CircleTests.cs, src/ACadSharp.Tests/Entities/EllipseTests.cs, src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/Entities/Arc.cs, src/ACadSharp/Entities/Circle.cs, src/ACadSharp/Entities/Ellipse.cs, src/ACadSharp/Entities/Entity.cs, src/ACadSharp/Entities/Hatch.BoundaryPath.Arc.cs, src/ACadSharp/Entities/Vertex3D.cs
Polygonal vertexes fix for ellipse and arc.
=> Issue 631 polygonal vertexes fix

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/MText.cs
MText default values for so it's visible when writing the file.
=> MText defaults fix

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/HookLineDirection.cs, src/ACadSharp/Entities/Leader.cs, src/ACadSharp/Entities/LeaderPathType.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
Fix for the value HasHookline read in dwg.
=> HasHookline as read only

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfStreamWriterBase.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/IDxfStreamWriter.cs, src/ACadSharp/IO/DXF/DxfWriter.cs, src/ACadSharp/IO/DXF/DxfWriterConfiguration.cs
Add the flag to write the optional values for dxf files.
=> issue-622 WriteOptional flag dxf

src/ACadSharp.Tests/Entities/AttributeDefinitionTests.cs, src/ACadSharp.Tests/Entities/CommonEntityTests.cs, src/ACadSharp.Tests/Entities/EntityTests.cs, src/ACadSharp.Tests/Entities/SplineTests.cs, src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/PolyLine3D.cs, src/ACadSharp/Entities/Spline.cs
PR to transfer the changes made in:
- https://github.com/DomCR/ACadSharp/pull/586
=> Issue 480 spline polygonalvertices transfer

src/ACadSharp.Tests/CadObjectTests.cs, src/ACadSharp.Tests/Objects/NonGraphicalObjectTests.cs, src/ACadSharp.Tests/Tables/TableEntryTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Extensions/CadObjectExtensions.cs, src/ACadSharp/Objects/CadDictionary.cs, src/ACadSharp/Objects/NonGraphicalObject.cs, src/ACadSharp/Tables/Collections/Table.cs, src/ACadSharp/Tables/TableEntry.cs
Clones aren't unsubscribed from the events of their main instance.
=> clone remove events

src/ACadSharp/IO/DWG/DwgStreamReaders/DwgMergedReader.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC18.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC18.cs
-  handle ByLayer = 0xC0000000
see #652
=> Reading and Writing ByLayer Color = 0xC0000000

src/ACadSharp.Tests/Entities/CommonEntityTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Dimension.cs
Link the dimension block to the BlockRecords table.
=> Dimension block link

src/ACadSharp/IO/SVG/SvgXmlWriter.cs
Quick fix for missing points that didn't apply the units.
=> svg point unit

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
Implement reading the FitPoints for SPLines.
=> SPLine FitPoints

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/UnderlayEntity.cs
Fix the Underlay entity clone method.
=> Issue 741 pdfunderlay clone

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/CadObject.cs, src/ACadSharp/Objects/CadDictionary.cs, src/ACadSharp/Objects/SortEntitiesTable.cs
Implement the `Clone()` method for `CadDictionary`.
=> CadDictionary clone

src/ACadSharp.Tests/IO/LocalSampleTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Arc.cs, src/ACadSharp/Entities/Circle.cs, src/ACadSharp/Entities/Ellipse.cs, src/ACadSharp/Entities/Entity.cs, src/ACadSharp/Entities/IEntity.cs, src/ACadSharp/Entities/Insert.cs, src/ACadSharp/Entities/Leader.cs, src/ACadSharp/Entities/LwPolyLine.cs, src/ACadSharp/Entities/Ray.cs, src/ACadSharp/Entities/Shape.cs, src/ACadSharp/Entities/Tolerance.cs, src/ACadSharp/Entities/XLine.cs
Implement the method `Explode` for insert entities.
=> Issue 745 insert explode

docs/CadDocumentDocs.md, docs/InsertDocs.md, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
Add documentation for the project.
=> Enhance documentation

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp.Tests/Tables/BlockRecordTests.cs, src/ACadSharp/Blocks/Block.cs, src/ACadSharp/Blocks/BlockTypeFlags.cs, src/ACadSharp/Header/CadHeader.cs, src/ACadSharp/Header/XClipFrameType.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgHeaderReader.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgHeaderWriter.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfBlocksSectionWriter.cs, src/ACadSharp/IO/Templates/CadBlockRecordTemplate.cs, src/ACadSharp/Tables/BlockRecord.cs
Resolve the unload xref when the file is created.
=> Issue 756 xref

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DXF/DxfReader.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
Fix for Multiline AttDef in dxf writer.
=> multiline attdef

src/ACadSharp.Tests/IO/DWG/DwgWriterSingleObjectTests.cs, src/ACadSharp.Tests/IO/LocalSampleTests.cs, src/ACadSharp.Tests/IO/RewriteSamplesTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs, src/ACadSharp/Objects/XRecord.Entry.cs
Fix for writing xrecords in dwg.
=> Dwg xrecords

src/ACadSharp.Tests/IO/RewriteSamplesTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Mesh.cs, src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs
Add the write function for mesh entities.
=> Mesh write fix

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DXF/DxfDocumentBuilder.cs, src/ACadSharp/IO/DXF/DxfReader.cs, src/ACadSharp/IO/DXF/DxfReaderConfiguration.cs
Add an option for dxf reader to create the defaults at the end of the reading operation.
=> create defaults for dxf

src/ACadSharp.Tests/IO/DXF/DxfWriterSingleObjectTests.cs, src/ACadSharp.Tests/IO/RewriteSamplesTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs, src/ACadSharp/IO/DXF/DxfWriter.cs
Fix for the object dictionary with default in dxf format.
=> dxf dictionary with default

src/ACadSharp.Tests/Entities/CommonEntityTests.cs, src/ACadSharp/Entities/Entity.cs, src/ACadSharp/Entities/IEntity.cs
Get active properties for entities.
=> Get active properties

src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Spline.cs, src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs, src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
Update the controlpoints from splines using fitpoints.
=> Issue 748 spline fitpoints update

src/ACadSharp.Tests/Entities/HatchTests.cs, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Hatch.cs, src/ACadSharp/Entities/HatchPattern.Line.cs, src/ACadSharp/Entities/HatchPattern.cs
Alter the HatchPattern when the scale or angle are changed.
=> Issue 782 hatch pattern scale

src/ACadSharp.Tests/Common/EntityFactory.cs, src/ACadSharp.Tests/Entities/HatchTests.cs, src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs, src/ACadSharp.Tests/Tables/Collections/TextStylesTableTests.cs, src/ACadSharp/Entities/CadWipeoutBase.cs, src/ACadSharp/Entities/Dimension.cs, src/ACadSharp/Entities/DimensionOrdinate.cs, src/ACadSharp/Entities/Hatch.BoundaryPath.Spline.cs, src/ACadSharp/Entities/Hatch.BoundaryPath.cs, src/ACadSharp/Entities/LwPolyLine.cs, src/ACadSharp/Entities/PolyLine.cs, src/ACadSharp/Entities/Spline.cs, src/ACadSharp/Entities/TextEntity.cs, src/ACadSharp/Tables/BlockRecord.cs
Refactor for the method addflag.
=> addflag refactor

README.md, src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/PolyLine.cs, src/ACadSharp/Entities/PolyfaceMesh.cs, src/ACadSharp/Entities/VertexFaceRecord.cs, src/ACadSharp/IO/DXF/DxfStreamReader/DxfEntitiesSectionReader.cs
Fix for the PolyfaceMesh clone() method.
=> Polyface mesh clone fix

src/ACadSharp/ACadSharp.csproj, src/ACadSharp/Entities/Hatch.BoundaryPath.Polyline.cs, src/ACadSharp/Header/CadHeader.cs
Fix the bulge value for polylines.
=> BoundaryPath.Polyline fix
