DomCR/ACadSharp

- ACadSharp.Tests/DxfMapTests.cs
- ACadSharp/Attributes/DxfSubClassAttribute.cs
- ACadSharp/DxfMap.cs
- ACadSharp/Entities/AttributeBase.cs
- ACadSharp/Entities/Vertex.cs
- ACadSharp/Entities/Vertex2D.cs
- ACadSharp/Entities/Vertex3D.cs
- ACadSharp/IO/DWG/DwgObjectSectionReader.cs
- ACadSharp/Tables/Collections/Table.cs
- ACadSharp/Tables/TableEntry.cs
DxfMap allows to create a class that links all the dxf codes with each property for all CadObjects
> Dxf CadObject mapper

- ACadSharp.Tests/CadDocumentTests.cs
- ACadSharp.Tests/Common/DocumentIntegrity.cs
- ACadSharp.Tests/IO/CadReaderTestsBase.cs
- ACadSharp.Tests/IO/DWG/DwgReaderTests.cs
- ACadSharp.Tests/IO/DXF/DxfReaderTests.cs
- ACadSharp/IO/CadReaderBase.cs
- ACadSharp/IO/DWG/DwgReader.cs
- ACadSharp/IO/DXF/DxfReader.cs
- CadDocument needs to create all the default objects if is not in the reader
- The document creates the tables but the handles need to be reassign during the reading
- ```BlockEnd``` and ```BlockEntity``` must be included in the document
> document integrity

- ACadSharp.Tests/Tables/BlockRecordTests.cs
- ACadSharp/CadObjectCollection.cs
- ACadSharp/DxfClassMap.cs
- ACadSharp/DxfMap.cs
- ACadSharp/Header/CadHeader.cs
- ACadSharp/PropertyReflection.cs
Upon my first review, I have found that reflection and list access are the immediate worst offenders at this point.  I ran a read & write operation as indicated below and found the following with a CAD DXF drawing that has roughly 22,000 items (Blocks & simple entities).  I would attach the DXF, but it is a private project file.
For this first pass, I tired to leave the base code alone as much as possible as my initial work on refactoring the Map classes to use static instances became wide reaching very fast.
With the current changes, we get a performance increase of roughly 5x on the first read and then 6.5x faster on subsequent reads over the baseline. The write performance is also now 4.7x faster.
Ran into a small reading issue with `DxfSectionReaderBase.readMapped` method where it was …
> Reading & Writing Performance Review Changes

- ACadSharp.Tests/IO/IOTestsBase.cs
This PR adds a lookup for AutoCAD installations if it does not exist in the default location.  Allows testing on version of AutoCAD from 2023 to 2021 LT and full.
> Extends AutoCAD Testing Versions

- ACadSharp/Entities/MText.cs
- ACadSharp/Entities/TextEntity.cs
- ACadSharp/IO/DWG/DwgObjectSectionReader.cs
- ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
- ACadSharp/IO/Templates/CadArcTemplate.cs
- ACadSharp/IO/Templates/CadInsertTemplate.cs
- ACadSharp/IO/Templates/CadTextEntityTemplate.cs
- ACadSharp/MathUtils.cs
- Documentation update and fix
- Rotation and AlignmentPoint linked to be coherent 
- Fix for the Rotation value not being set - Only for 2D
> MText refactoring

- ACadSharp/IO/DWG/DwgStreamWriters/DwgHandleWriter.cs
When using the DwgWriter, a not initialized exception occures in net48 version.
Null exception when using Net48
> handleMap not initialized exception

- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
Reading some dwg-files results null values fix
> Issue 178 

- ACadSharp.Tests/Common/Factory.cs
- ACadSharp.Tests/IO/DWG/DwgWriterTests.cs
- ACadSharp.Tests/IO/IOTests.cs
- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs
- ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
- ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
- ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs
- ACadSharp/IO/DWG/DwgWriter.cs
- ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs
- ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
- ACadSharp/IO/Templates/CadLayoutTemplate.cs
- ACadSharp/IO/Templates/CadXRecordTemplate.cs
- ACadSharp/Objects/Layout.cs
- ACadSharp/Objects/XRecrod.cs
Implement the `CadDictionary` and the `Objects` in the DwgWriter
Objects:
* https://github.com/DomCR/ACadSharp/pull/189
* https://github.com/DomCR/ACadSharp/pull/190 (Note: complex object, needs investigation)
> Dwg writer Objects

- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- ACadSharp/Objects/MultiLeaderAnnotContext.cs
Fix for index out of range in readmultileader in `DwgObjectReader`
Consider to implement the transformation matrix in multileader context using `CSMath.Matrix4`
> Issue 198 index out of range in readmultileader

- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- ACadSharp/Objects/MultiLeaderAnnotContext.cs
Short description about this PR
- Add the links of issues or PR related to this one.
- Things to consider during the review of this PR.
> Replace double[] with Matrix4

- ACadSharp/Entities/TextEntity.cs
Removed internal linking of the `TextEntity.Rotation` and `TextEntity.AlignmentPoint` properties.
Fixes issues with rotation adjusting AlignmentPoint and AlignmentPoint adjusting the rotations.  After a bit of research, the AutoCad AlignmentPoint is the location where the text is to be inserted in conjunction with the VerticalAlignment and HorizontalAlignment.  Based upon certain configurations of the enumns, either the InsertPoint or the AlignmentPoint is used to determine where the text is to be inserted.  As far as I can tell, it does not have anything to do with the Rotation, at least as far as 2D goes.  I do not have time to experiment with 3d rotations. Ref #86.
For reference, the `InsertionPoint`s below are the bottom left grips while the `AlignmentPoint`s are the other grips on …
> Text rotation fix

- ACadSharp/Entities/Leader.cs
- ACadSharp/IO/Templates/CadLeaderTemplate.cs
-  Leader: new property AssociatedAnnotation
-  CadLeaderTemplate: implementation added: Build
> #230 fixed

- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
ignore DwgColor to avoid a corrupted document.
> ignore DwgColor

- ACadSharp.Tests/Tables/TableEntryTests.cs
- ACadSharp/OnNameChangedArgs.cs
- ACadSharp/Tables/Collections/Table.cs
- ACadSharp/Tables/TableEntry.cs
Allows for the user to change a table entry name updating the table key.
> Table entry name change

- ACadSharp/Entities/Hatch.BoundaryPath.Polyline.cs
- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
In the existing algorithm, when BoundaryPath of Polyline type had convexities, they were overwritten. This is incorrect according to the DWG format specification.
Below I offer my solution to the problem.
- Fixed #282
- I've changed the way the bulges are stored. Now they are stored as a list.
- I had to change the record loop from foreach to for.
> Fixed bug in reading bulges for Hatch.BoundaryPath.Polyline from DWG file

- ACadSharp/CadDocument.cs
- ACadSharp/Tables/Layer.cs
- ACadSharp/Tables/TextStyle.cs
> Issue-290 Default Layer color

- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
Fix for the Multileader `DwgReader` Advance(2) fix due a type mismatch.
> Multileader DwgReader jump fix

- ACadSharp.Examples/Common/NotificationHelper.cs
- ACadSharp.Examples/Program.cs
- ACadSharp.Examples/ReaderExamples.cs
- ACadSharp.Tests/IO/LocalSampleTests.cs
- ACadSharp.Tests/Internal/DwgObjectWriterTests.cs
- ACadSharp/IO/CadDocumentBuilder.cs
- ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- ACadSharp/IO/DXF/DxfDocumentBuilder.cs
- ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs
- ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
- ACadSharp/IO/Templates/CadHatchTemplate.CadBoundaryPathTemplate.cs
- ACadSharp/IO/Templates/CadLineTypeTemplate.cs
- ACadSharp/IO/Templates/CadMLineStyleTemplate.cs
- ACadSharp/IO/Templates/DwgGroupTemplate.cs
- ACadSharp/IO/Templates/ICadObjectTemplate.cs
Modify the Builder to improve the reading performance.
The stress files have a size of 115MB for dxf and 24MB for dwg.
> Increase reading performance

- ACadSharp.Tests/IO/LocalSampleTests.cs
- ACadSharp/IO/Templates/CadDictionaryTemplate.cs
- ACadSharp/Objects/CadDictionary.cs
Fix for `CadDictionary` entries that have a different key than their name.
> Separate the dictionary key from the entry name

- ACadSharp.Tests/IO/CadReaderTestsBase.cs
- ACadSharp/IO/CadReaderBase.cs
- ACadSharp/IO/DWG/DwgReader.cs
- ACadSharp/IO/DXF/DxfReader.cs
Fix to setup the default value for `SummaryInfo` when reading a file.
> fix SummaryInfo being null

- ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
Ignore MultiLeaderStyle for DwgWriter to avoid the recover error.
Expected fix:
- https://github.com/DomCR/ACadSharp/pull/385
> ignore MultiLeaderStyle

- ACadSharp.Tests/Objects/CadDictionaryTests.cs
- ACadSharp/Objects/CadDictionary.cs
Fixed `TryAdd` method, ensure that the `CadDictionary` will have no duplicates and added dedicated tests.
> caddictionary tryadd always returns false 

- ACadSharp/GroupCodeValue.cs
After testing with a few DWG files with XRecords in it I've realized that the documentation related to:
"390-399 String representing hex handle value"
Is only valid for DXF, the values stored in DWG are in `ulong` format like a handle should, giving the current implementation of the `GroupCodeValueType` transformation the value has been assigned to `ObjectId` instead of `Handle`.
> Fix XRecord group code

- src/ACadSharp.Tests/Tables/BlockRecordTests.cs
- src/ACadSharp.Tests/Tables/LayerTests.cs
- src/ACadSharp.Tests/Tables/TableEntryTests.cs
- src/ACadSharp/Tables/AppId.cs
- src/ACadSharp/Tables/DimensionStyle.cs
- src/ACadSharp/Tables/Layer.cs
- src/ACadSharp/Tables/LineType.cs
- src/ACadSharp/Tables/TableEntry.cs
- src/ACadSharp/Tables/TextStyle.cs
- src/ACadSharp/Tables/UCS.cs
- src/ACadSharp/Tables/View.cs
Fix the clone method for all the table entries.
> Table entries clone fix

- src/ACadSharp/Entities/Arc.cs
Fix for the method `PolygonalVertexes()` where the center is not added to the vertices.
> Arc PolygonalVertexes fix

- src/ACadSharp.Tests/IO/LocalSampleTests.cs
- src/ACadSharp/Entities/Hatch.cs
- src/ACadSharp/Entities/HatchPattern.cs
Fix for the method `Hatch.Clone()` and `HatchPattern.Clone()`.
> Issue 458 hatch clone fix

- README.md
- Just adding a link in the README.md file to the Shared Project: CSUtilities.
* [ X ] Something awesome.
- #434
> Link to Shared Project

- src/ACadSharp.Tests/IO/LocalSampleTests.cs
- src/ACadSharp.Tests/IO/MultiLeaderTests.cs
- src/ACadSharp.Tests/IO/ViewportTests.cs
- src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs
- src/ACadSharp/Entities/Viewport.cs
- src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
- src/ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs
- src/ACadSharp/IO/Templates/CadDictionaryTemplate.cs
- src/ACadSharp/IO/Templates/CadViewportTemplate.cs
- src/ACadSharp/Objects/Collections/ObjectDictionaryCollection.cs
- src/ACadSharp/Objects/Collections/ScaleCollection.cs
- src/ACadSharp/Objects/XRecord.Entry.cs
- src/ACadSharp/Objects/XRecrod.cs
Assign the scale to the viewport.
> Viewport scale

- src/ACadSharp.Tests/Common/DocumentIntegrity.cs
- src/ACadSharp.Tests/IO/CadReaderTestsBase.cs
- src/ACadSharp.Tests/IO/DWG/DwgReaderTests.cs
- src/ACadSharp.Tests/IO/DXF/DxfReaderTests.cs
- src/ACadSharp/Entities/CadWipeoutBase.cs
- src/ACadSharp/Entities/RasterImage.cs
- src/ACadSharp/Entities/Wipeout.cs
- src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
- src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
- src/ACadSharp/IO/Templates/CadImageTemplate.cs
- src/ACadSharp/Objects/ImageDefinition.cs
- src/ACadSharp/Objects/ImageDefinitionReactor.cs
Image reactor will not be used, it doesn't seem to have an effect in the file so the object will be ignored.
Raster image constructor has been refactor to be easier to use.
> Issue 538 image reactor

- README.md
- src/ACadSharp.Tests/IO/DWG/DwgWriterSingleObjectTests.cs
- src/ACadSharp.Tests/Internal/DwgHeaderWriterTests.cs
- src/ACadSharp/Header/CadHeader.cs
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgClassesWriter.cs
- src/ACadSharp/IO/DWG/DwgWriter.cs
Fix for the `DxfClasses` section in the `DwgWriter` not  being compressed.
Fix the `DwgWriter` for version AC1027 by including the `MaintenanceVersion` value.
> Dwg writer compressed

- src/ACadSharp/Exceptions/CadNotSupportedException.cs
- src/ACadSharp/IO/DWG/DwgStreamReaders/DwgClassesReader.cs
- src/ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderBase.cs
- src/CodeMaid.config
Found invalid values for some cases of dwg files, the fix consist into change the type of some values to the newer versions of the file.
> Dwg DxfClasses reader fix

- src/ACadSharp.Tests/CadDocumentTests.cs
- src/ACadSharp/ACadSharp.csproj
- src/ACadSharp/CadDocument.cs
Performance fix for the `addCadObject` to the `CadDocument` to increase the speed and avoid unnecessary iterations.
> Issue 605 cad document performance fix

- src/ACadSharp/IO/SVG/SvgXmlWriter.cs
Use writestring to allow escaping special symbols.
When a string/text contains & or other special symbols it should be escaped, not written raw to svg.
> Escape special characters when writing strings to svg

- src/ACadSharp.Tests/IO/LocalSampleTests.cs
- src/ACadSharp/ACadSharp.csproj
- src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
- src/ACadSharp/IO/Templates/CadMLeaderStyleTemplate.cs
Transfer files for the DWG reader and writer for the MLeader style from:
- https://github.com/DomCR/ACadSharp/pull/641
> transfer files for mleader dwg

- src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs
- src/ACadSharp/ACadSharp.csproj
- src/ACadSharp/IO/CadWriterConfiguration.cs
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
Fix the writing for older versions XRecord.
There is an issue with some XRecords pointing to handles or objects that `ACadSharp` doesn't support, for example adding this guard to the method writeXRecords for a dwg file fixes some of the recovery issues:
```C#
if(entry.Value.ToString() == "MATERIAL")
{
continue;
}
```
It seems that the `XRecord` is expecting or indicating a material (not specified there is only the name) but Autocad is not able to read it so is discarded.
> issue-649 XRecord

- src/ACadSharp.Tests/Tables/BlockRecordTests.cs
- src/ACadSharp/ACadSharp.csproj
- src/ACadSharp/Objects/Layout.cs
- src/ACadSharp/Tables/BlockRecord.cs
Fix for the `Clone()` method and Blocks associated to a `Layout`.
Changes in functionality and behavior:
- The cloned `Block` will be unlinked from the `Layout`.
- The cloned `Layout` will keep the `Block`.
> Issue 679 block record layout clone

- src/ACadSharp.Tests/IO/LocalSampleTests.cs
- src/ACadSharp.Tests/Objects/SortEntitiesTableTests.cs
- src/ACadSharp.Tests/Tables/BlockRecordTests.cs
- src/ACadSharp/ACadSharp.csproj
- src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
- src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
- src/ACadSharp/IO/Templates/CadSortensTableTemplate.cs
- src/ACadSharp/Objects/SortEntitiesTable.Sorter.cs
- src/ACadSharp/Objects/SortEntitiesTable.cs
- src/ACadSharp/Tables/BlockRecord.cs
Fix for `SortEntitiesTable` and exploration of how this works on the view.
- Entities can be repeated.
- The entities are drawn using the handle value, unless they are assigned to the `SortEntitiesTable`.
- `SortHandle` overrides the `Entity.Handle` value for the drawing order.
- Adding entities with other owners doesn't take any negative effect.
The drawing contains a 2 lines and 1 wipeout, 1 line is below the other is above. The sort table looks:
```C#
var below = doc.GetCadObject<Line>(598);
var above = doc.GetCadObject<Line>(599);
var wipeout = doc.GetCadObject<Wipeout>(600);
```
{600 | LINE:599} //Line above
{599 | WIPEOUT:600}  //Wipeout
Adding the following entry doesn't change any order:
```C#
sort.AddEntity(below, wipeout.Handle);
```
{600 | LINE:598}
Adding the following entry …
> issue-696 sortentities fix

- src/ACadSharp/Entities/Hatch.cs
- src/ACadSharp/Entities/Spline.cs
The for to transform FitPoints must run to Count not to Capacity
Unintended Change of Hatch was rolled back.
fixes #666
> 20250703 13  666 spline transform fails
